### ISSUE TITLE
Difference between negative integers and equivalent negative fractions?

### ISSUE THREAD

**Issue by timsherwood** [GDeLaurentis/pyadic#2]
Thank you for this package, it has been really helpful trying to build an intuition for p-adic numbers.  In playing around I came across an odd behavior that think may be a bug.  Specifically, when converting from a negative integer -x I seem to get a different PAdic than when I convert from the equivalent trivial fraction(-x,1).  

>>> PAdic(-2, 2, 4)
1*2 + 1*2^2 + 1*2^3 + O(2^4)
>>> PAdic(Q(-2,1), 2, 4)
1*2 + 1*2^2 + 1*2^3 + O(2^5)
>>> Q(-2,1) == -2
True

**Comment by GDeLaurentis** [comment]
Hi tim, I am glad the package has been helpful, and thanks for pointing out this behavior. I agree this is a bug, specifically with the precision handling -- the `O(p^k)` tem -- upon instantiation of `PAdic` from a number which is negative and proportional to the prime `p`. In [commit 80857f3](https://github.com/GDeLaurentis/pyadic/commit/80857f3d6a40ab8b3e098e932a73250e5aeba39e) I have added an `abs` to the function which looks for factors of the prime when `__init__` of `PAdic` is called.  I have also added a test to check the change. If you pull the repo you should now see the following behavior:

```
-PAdic(2, 2, 4) == PAdic(-2, 2, 4) == PAdic(Q(-2, 1), 2, 4)
True
-PAdic(2, 2, 4)
1*2 + 1*2^2 + 1*2^3 + 1*2^4 + O(2^5)
```

**Comment by timsherwood** [comment]
Thank you for the super prompt response, Giuseppe -- I can confirm that seems to have fixed it.
